stages:
  - name: Test
    steps:
      - runScriptConfig:
          image: node:latest
          shellScript: |-
            npm install
            npm audit --audit-level=moderate
            npm run lint
            npm run test
  - name: Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: awcloud/tenantapi:${CICD_EXECUTION_SEQUENCE}
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deploy/deployment-dev.yaml
      - applyYamlConfig:
          path: ./deploy/deployment-stag.yaml
        #- applyYamlConfig:
        #    path: ./deploy/deployment-prod.yaml
        when:
          branch: master
          event: push
timeout: 60
notification: {}
